services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 5173:5173
    working_dir: /home/web
    volumes:
      - ./web/:/home/web
      - node_modules_volume:/home/web/node_modules
    command: bash -c "npm install && npm run dev"

volumes:
  node_modules_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/web/node_modules
      o: bind
