services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 5173:5173
    working_dir: /home/web
    volumes:
      - ./api/:/home/api
      - ./web/:/home/web
      - web_node_modules_volume:/home/web/node_modules
    command: bash -c "npm install && npm run dev"

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    working_dir: /home/api
    volumes:
      - ./api/:/home/api
      - /var/run/docker.sock:/var/run/docker.sock
      - api_node_modules_volume:/home/api/node_modules
    command: bash -c "npm install && npm run dev"

volumes:
  web_node_modules_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/web/node_modules
      o: bind
  api_node_modules_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/api/node_modules
      o: bind
